### PR TITLE
update constructor syntax for solidity 0.4.23 in numerous contracts

### LINKED ISSUE #932: Contracts using old-style constructors.
## 🎉 Description

- [ ] 🐛 This is a bug report.
- [ ] 📈 This is a feature request.
- [x] 💻 This is a suggestion for the future.

Constructor functions for contracts still using the form:
```solidity
  function <Contract_Name>(<params>) {}
```
Instead of the new constructor style with Solidity 0.4.23:
```solidity
  constructor(<params>) {}
```

## 💻 Environment

Truffle 4.1.8
Solidity 0.4.23

## 📝 Details

We should adopt the new constructor style since it will still throw deprecation warnings in future releases of Solidity.

## 👍 Other Information

https://solidity.readthedocs.io/en/v0.4.23/contracts.html#creating-contracts

### PR DESCRIPTION
**Pull request by pemulis**
# 🚀 Description

This eliminates a lot of compiler warnings.
- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

_(edit: the linter error is resolved!)_
The linter throws an error (below) on all of the changed contracts at the constructor line, but I think the linter is wrong, not the constructor.

`error    Syntax error: unexpected token ( `

Closes #932

### CODE REVIEW

**Comment by pemulis** [comment]
I'm curious why tests are failing and wonder if this is an issue with Ganache.

```
8.82s$ npm run test
> openzeppelin-solidity@1.9.0 test /home/travis/build/OpenZeppelin/openzeppelin-solidity
> scripts/test.sh
Starting our own ganache instance
Error parsing /home/travis/build/OpenZeppelin/openzeppelin-solidity/contracts/DayLimit.sol: ParsedContract.sol:19:14: ParserError: Expected identifier, got 'LParen'
  constructor(uint256 _limit) public {
             ^
Compilation failed. See above.
```

**Comment by naveensrinivasan** [comment]
@pemulis  The tests are failing because the `solc` being used is version `Solidity v0.4.21 (solc-js)` https://travis-ci.org/OpenZeppelin/openzeppelin-solidity/jobs/372851241#L2432

The new `constructor` keyword was release in `0.4.22` https://github.com/ethereum/solidity/releases/tag/v0.4.22.

I would recommend as part of the PR also update the tests dependecies which should fix this.
HTH

**Comment by pemulis** [comment]
Thanks @naveensrinivasan! I'll take care of that.

**Comment by pemulis** [comment]
Looks like the tests are all working now, so the constructor() update is good to go when you want to update the OZ project in a couple of weeks.

**Comment by adklempner** [comment]
@Shrugs 0.4.22 adds error reason strings for `revert` and `require`, would love to see them in OZ

**Comment by frangio** [comment]
@elopio We don't because solc comes with Truffle.

**Comment by shrugs** [comment]
@pemulis Let's upgrade all of the contracts to `^0.4.23`. Running a quick grep `grep -r -P "pragma solidity \^0.4.(?:(?\!23).)" --exclude-dir node_modules --include=*.sol`

shows the following contracts are still on older versions:

```
contracts/mocks/SafeMathMock.sol:pragma solidity ^0.4.21;
contracts/mocks/SecureTargetBounty.sol:pragma solidity ^0.4.21;
contracts/mocks/ReentrancyAttack.sol:pragma solidity ^0.4.21;
contracts/mocks/BouncerMock.sol:pragma solidity ^0.4.18;
contracts/mocks/MessageHelper.sol:pragma solidity ^0.4.21;
contracts/mocks/LimitBalanceMock.sol:pragma solidity ^0.4.21;
contracts/mocks/MerkleProofWrapper.sol:pragma solidity ^0.4.21;
contracts/mocks/InsecureTargetBounty.sol:pragma solidity ^0.4.21;
contracts/mocks/WhitelistMock.sol:pragma solidity ^0.4.21;
contracts/mocks/ECRecoveryMock.sol:pragma solidity ^0.4.21;
contracts/mocks/ERC721BasicTokenMock.sol:pragma solidity ^0.4.21;
contracts/mocks/MathMock.sol:pragma solidity ^0.4.21;
contracts/token/ERC827/ERC827Token.sol:pragma solidity ^0.4.21;
contracts/token/ERC827/ERC827.sol:pragma solidity ^0.4.21;
contracts/token/ERC20/StandardToken.sol:pragma solidity ^0.4.21;
contracts/token/ERC20/StandardBurnableToken.sol:pragma solidity ^0.4.18;
contracts/token/ERC20/ERC20.sol:pragma solidity ^0.4.21;
contracts/token/ERC20/SafeERC20.sol:pragma solidity ^0.4.21;
contracts/token/ERC20/PausableToken.sol:pragma solidity ^0.4.21;
contracts/token/ERC20/ERC20Basic.sol:pragma solidity ^0.4.21;
contracts/token/ERC20/BurnableToken.sol:pragma solidity ^0.4.21;
contracts/token/ERC20/BasicToken.sol:pragma solidity ^0.4.21;
contracts/token/ERC20/MintableToken.sol:pragma solidity ^0.4.21;
contracts/token/ERC721/ERC721Receiver.sol:pragma solidity ^0.4.21;
contracts/token/ERC721/ERC721.sol:pragma solidity ^0.4.21;
contracts/token/ERC721/ERC721BasicToken.sol:pragma solidity ^0.4.21;
contracts/token/ERC721/ERC721Holder.sol:pragma solidity ^0.4.21;
contracts/token/ERC721/DeprecatedERC721.sol:pragma solidity ^0.4.21;
contracts/token/ERC721/ERC721Basic.sol:pragma solidity ^0.4.21;
contracts/ReentrancyGuard.sol:pragma solidity ^0.4.21;
contracts/access/SignatureBouncer.sol:pragma solidity ^0.4.18;
contracts/payment/PullPayment.sol:pragma solidity ^0.4.21;
contracts/lifecycle/Pausable.sol:pragma solidity ^0.4.21;
contracts/crowdsale/emission/MintedCrowdsale.sol:pragma solidity ^0.4.21;
contracts/crowdsale/distribution/PostDeliveryCrowdsale.sol:pragma solidity ^0.4.21;
contracts/crowdsale/distribution/FinalizableCrowdsale.sol:pragma solidity ^0.4.21;
contracts/crowdsale/validation/IndividuallyCappedCrowdsale.sol:pragma solidity ^0.4.21;
contracts/crowdsale/validation/WhitelistedCrowdsale.sol:pragma solidity ^0.4.21;
contracts/Bounty.sol:pragma solidity ^0.4.21;
contracts/math/SafeMath.sol:pragma solidity ^0.4.21;
contracts/math/Math.sol:pragma solidity ^0.4.21;
contracts/ownership/Claimable.sol:pragma solidity ^0.4.21;
contracts/ownership/rbac/Roles.sol:pragma solidity ^0.4.21;
contracts/ownership/rbac/RBAC.sol:pragma solidity ^0.4.21;
contracts/ownership/HasNoTokens.sol:pragma solidity ^0.4.21;
contracts/ownership/NoOwner.sol:pragma solidity ^0.4.21;
contracts/ownership/Contactable.sol:pragma solidity ^0.4.21;
contracts/ownership/DelayedClaimable.sol:pragma solidity ^0.4.21;
contracts/ownership/Whitelist.sol:pragma solidity ^0.4.21;
contracts/ownership/CanReclaimToken.sol:pragma solidity ^0.4.21;
contracts/ownership/HasNoContracts.sol:pragma solidity ^0.4.21;
contracts/ECRecovery.sol:pragma solidity ^0.4.21;
contracts/MerkleProof.sol:pragma solidity ^0.4.21;
contracts/AddressUtils.sol:pragma solidity ^0.4.21;
```

I also confirmed at all of the `constructor()` args were changed, so that part looks good to me.

**Pull request merged**
