### PR TITLE
Update ReentrancyGuard for EIP 1283

### PR DESCRIPTION
**Pull request by BrendanChou**
Per https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1283.md, the old way of doing reentrancy will soon be more efficient (~400 gas). Uses uint256 instead of bool since the native word size of the EVM is 256 bits and this will probably be the most gas-optimized solution regardless of how many rounds of optimization are used.

### CODE REVIEW

**Comment by frangio** [comment]
Thanks @BrendanChou! I was waiting for this. :smile:

When is Constantinople landing on mainnet?

We have to be careful with how this affects [openzeppelin-eth](https://github.com/OpenZeppelin/openzeppelin-eth). We will probably need to add a function to reset the value of `_guardCounter`, or alternatively deprecate that state variable and use a new storage slot.

**Comment by BrendanChou** [comment]
Constantinople should be live on Jan 16. Happens at exactly block # 7,080,000

**Comment by BrendanChou** [comment]
Changing the name as it is now uncertain whether EIP 1283 will be included in the Constantinople hard-fork

**Comment by nventuro** [comment]
I guess this will have to wait :/

**Comment by nventuro** [comment]
Closing this, given that EIP1283 was pulled out from Constantinople.

**Pull request closed without merging**
