### PR TITLE
Refactor/reentrancy guard gas optimization #1056

### LINKED ISSUE #1056: ReentrancyGuard gas usage optimization
## 🎉 Description

`ReentrancyGuard` is very useful contract to prevent reentrancy attack and is actively used. But there is associated performance (gas usage) penalty: about 25k gas per invocation. This could be optimized to 10k gas pre invocation: 2.5x times. A PR will follow.

- [x] 📈 This is a feature request.

## 💻 Environment

- OpenZeppelin v1.10.0
- Deploying to Ganache v6.1.0
- Deploying with truffle v4.1.11

## 📝 Details

The problem with the current implementation is that it uses boolean flag and boolean value `false` is stored in contract storage as 0. Changing storage cell content from 0 to non-zero costs 20k gas and it's happening on each invocation of `nonReentrant` modifier, because at the end of each invocation cell content is changed back to zero. As a result, each call to `nonReentrant` costs 25k gas: 20k for writing to zeroed storage cell and 5k for writing to non-zero storage cell.

Proposed solution is to never return to zero. Each call to `nonReentrant` will use non-zero integer constants to represent state of the guard.

## 🔢 Code To Reproduce Issue

It could be seen in Remix that execution cost of each call to `Test.test()` is 25929 gas.

```
pragma solidity ^0.4.24;


/**
 * @title Helps contracts guard agains reentrancy attacks.
 * @author Remco Bloemen <remco@2π.com>
 * @notice If you mark a function `nonReentrant`, you should also
 * mark it `external`.
 */
contract ReentrancyGuard {

  /**
   * @dev We use a single lock for the whole contract.
   */
  bool private reentrancyLock = false;

  /**
   * @dev Prevents a contract from calling itself, directly or indirectly.
   * @notice If you mark a function `nonReentrant`, you should also
   * mark it `external`. Calling one nonReentrant function from
   * another is not supported. Instead, you can implement a
   * `private` function doing the actual work, and a `external`
   * wrapper marked as `nonReentrant`.
   */
  modifier nonReentrant() {
    require(!reentrancyLock);
    reentrancyLock = true;
    _;
    reentrancyLock = false;
  }

}

contract Test is ReentrancyGuard {
    function test() external nonReentrant {
    }
}
```

## 👍 Other Information

PR will follow.

### PR DESCRIPTION
**Pull request by Eenae**
Fixes #1056 

# 🚀 Description

Implemented solution proposed in the issue. Using integer constants to represent state of the guard. Not using `enum {Dummy, Free, Locked}` because solidity documentation as far as I can see does't provide necessary guarantees on underlying integer values of enum members (again, our goal is to never touch 0).

It could be seen in Remix that execution cost of each empty nonReentrant call is 10390 gas now.

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by BrendanChou** [comment]
I believe changing to uint8 will save storage costs in the case that other storage variables can fit within the same 32bit word

**Comment by Eenae** [comment]
> I believe changing to uint8 will save storage costs in the case that other storage variables can fit within the same 32bit word

Yes, but with ~500 gas overhead on read-write. Was't sure it worths it in a long run.

**Comment by BrendanChou** [comment]
Where does that ~500 gas overhead come from?

**Comment by Eenae** [comment]
> Where does that ~500 gas overhead come from?

Before writing 1 byte solidity has to read (200 gas) current 32-bytes slot and merge 1 byte into it and finally write back 32-bytes slot. Mechanics is the same as in partial writes of disk sectors. This extra gas overhead is noted in solidity docs afair.

**Comment by BrendanChou** [comment]
Either way, you have to SSTORE and SLOAD a whole word (32 bytes). I'm not sure why 500 gas would be needed to do a bitmask.

**Comment by Eenae** [comment]
You don't need SLOAD to write uint. But this is not the case for uint8.

**Comment by BrendanChou** [comment]
Ah makes sense, you're right

**Comment by axic** [comment]
> no way to retrieve those values from outside Solidity (i.e. they are not specified in the ABI, nor anywhere else).

It is on the roadmap though: https://github.com/ethereum/solidity/issues/1602

**Pull request merged**
