### PR TITLE
Adds ERC1132 interface and sample implementation

### PR DESCRIPTION
**Pull request by maxsam4**
# 🚀 Description

Adds sample implementation of ERC1132

Read more about EIP1132 on https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1132.md

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by nventuro** [comment]
Hey @maxsam4, thanks for contributing to OpenZeppelin!

This looks heavily inspired by https://github.com/nitika-goel/lockable-token (in which you're a main contributor), which sadly has no license. @elopio is our licensing expert, but from my understanding it would not be ok for us to simply have a copy the code in a case such as this.

Anyhow, have you checked our [`TokenTimelock`](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/v1.12.0/contracts/token/ERC20/TokenTimelock.sol) contract? We're also doing some experimentation with escrows in the [`escrow-exploration`](https://github.com/OpenZeppelin/openzeppelin-solidity/tree/escrow-exploration/contracts/payment) branch. If those do not fit your needs, could you expand a bit as to why?

Thanks again!

**Comment by maxsam4** [comment]
Hi @nventuro, Thanks for your feedback!

This is in fact inspired by @nitika-goel's Implementation. I never noticed that the original implementation is missing the license. I'll get in touch with @nitika-goel to sort it out.

The TokenTimeLock is a very basic implementation of time locking which makes it hard to be used in the applications that depend on the locked tokens (for example, reward distribution based on locked/staked amount). 

There are various reasons why we didn't opt to use an escrow for locking and they are explained on https://github.com/ethereum/EIPs/issues/1132 Please, have a look.

If I remember correctly, the TokenEscrow contract didn't exist in openzepplin's suite of contracts when the EIP for lockable token was created. In any case, It still does not achieve the goals of an inherently lockable token that are mentioned in the EIP.

I understand that increasing adoption for a new contract will be tough so I have also implemented an Escrow like functionality which does not depend on an Owner and overcomes a few other drawbacks of escrows. It's still a WIP but you can get the idea from https://github.com/somish/govblocks-protocol/blob/master/contracts/TokenProxy.sol

**Comment by nitika-goel** [comment]
I've added a license to the original [repo](https://github.com/nitika-goel/lockable-token ).
Thanks @nventuro and @maxsam4 for your feedback. The prime purpose of the ERC is to keep a record of the tokens locked under the same contract. This gives us the following advantages:

1. No additional trust on escrow contract / stake manager
2. No approval process for token transfer
3. Better user experience as the user needs to claim the amount back from a single contract
4. Ability for the user to track their true token balance / token activity
5. Ability for the user to utilize their locked tokens within the token ecosystem. For example, locked tokens can be used for governance.

We are using this in 2 projects already - [GovBlocks](https://github.com/somish/govblocks-protocol) and [Nexus Mutual](https://nexusmutual.io/).

**Comment by mswezey23** [comment]
From ValidityLabs - we are seeing clients request such features that this, ERC1132, would be of great value

**Comment by nventuro** [comment]
Closing due to staleness - the EIP also doesn't seem to have moved forward much.

**Pull request closed without merging**
