### PR TITLE
Change prepack npm script to prepare

### PR DESCRIPTION
**Pull request by frangio**
npm allows installing a dependency directly from a git repository, but in those cases the build script needs to run locally on the computer that is installing. The `prepack` script is supposed to accomplish that but there is bug in npm and it runs without dev dependencies installed (https://github.com/npm/npm/issues/19564). Switching to `prepare` fixes that. As a side effect, now running `npm install` in the project will not only install dependencies but also run the build script, but this is not a big deal IMO.

>prepare: Run both BEFORE the package is packed and published, on local npm install without any arguments, and when installing git dependencies (See below). This is run AFTER prepublish, but BEFORE prepublishOnly.

>prepack: run BEFORE a tarball is packed (on npm pack, npm publish, and when installing git dependencies)

### CODE REVIEW

**Comment by nventuro** [comment]
Any idea why the CI build is failing? The log looks cryptic.

**Comment by frangio** [comment]
I don't know. It might be a problem with the cache of dependencies because we changed dependencies in #1732. Let's check after that is merged.

**Comment by frangio** [comment]
Closing as we were not able to solve the above issue...

**Comment by nventuro** [comment]
Maybe this issue is related? https://github.com/trufflesuite/truffle/issues/1659

**Comment by frangio** [comment]
Seems to be the same thing, yeah.

**Pull request closed without merging**
