### PR TITLE
Promisify web3 sync requests in tests

### LINKED ISSUE #999: Stop using syncronous HTTP requests
## 🎉 Description

- [x] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

It's kinda both.

## 📝 Details

Syncronous HTTP requests are deprecated in upcoming web3 version and provider-engine doesn't support them.
We use them in tests extensively, but it's mostly `web3.eth.getBalance`.
Let's remove them and be future-proof!

### PR DESCRIPTION
**Pull request by arun1595**
Fixes #999

# 🚀 Description

Makes use of the `toPromise` helper already present in the codebase to promisify `web3.eth.getBalance` function calls throughout the tests.

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [ ] ✅ I've added tests where applicable to test my new functionality.
- [ ] 📖 I've made sure that my contracts are well-documented.
- [ ] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by arun1595** [comment]
@LogvinovLeon Done. Let me know if I missed something. Thanks!

P.S. I can squash the commits before the PR is good to merge.

**Comment by LogvinovLeon** [comment]
Could you please rebase your changes of the latest `master` branch?

**Comment by LogvinovLeon** [comment]
@shrugs Any chance you or any other maintainer can review that?

**Comment by arun1595** [comment]
@LogvinovLeon Sure, let me do it :slightly_smiling_face:

**Comment by shrugs** [comment]
hmm, SOLC_NIGHTLY is failing because of an ECRecovery call throwing instead of returning `0x0`. Investigating.

**Pull request merged**
