### PR TITLE
Add left shift operation to SafeMath

### LINKED ISSUE #626: SafeMath - support for shift-left
Perhaps you can add support for shift-left in the SafeMath library:

```
function shl(uint256 x, uint8 y) internal pure returns (uint256) {
    uint256 z = x << y;
    assert((z >> y) == x);
    return z;
}
```

### PR DESCRIPTION
**Pull request by ernestas2k**
- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](/docs/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters (`npm run lint:all:fix`) and fixed any issues.

Fixes #626

---

# 🚀 Description
Added left shift operation to SafeMath

### CODE REVIEW

**Comment by ernestas2k** [comment]
@facuspagnuolo take a look again!

**Comment by Shrugs** [comment]
@facuspagnuolo can you review again? LGTM, but math isn't my specialty.

**Comment by wbt** [comment]
If this is merged, we may want to also update the corresponding functionality in [PR#1484](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1484).

**Comment by nventuro** [comment]
Closing due to staleness. I'm interested in this requirement though, @ernestas2k what is it that you needed this for?

**Comment by ernestas2k** [comment]
@nventuro I think you're safe to close this, it was just a contribution to solve https://github.com/OpenZeppelin/openzeppelin-solidity/issues/626

**Pull request closed without merging**
