### PR TITLE
ERC20 internal transfer method

### PR DESCRIPTION
**Pull request by k06a**
# 🚀 Description

Allow ERC20 subclasses to perform transfers with own rules. For example by providing senders signature or something else.

Just extracted common `transfer` and `transferFrom` code into internal `_transfer` method.

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:fix`).

### CODE REVIEW

**Comment by frangio** [comment]
Yeah I think this makes a lot of sense to have.

@k06a I'm curious, have you run into the need to use this?

**Comment by k06a** [comment]
@frangio @nventuro I browsed the latest version of ERC20.sol and decided this API was missed. Some token creators would like to provide token transfers based on holder signatures for example.

A while ago I developed the library for this: https://github.com/bitclave/Feeless. Do you think this kind of functionality could be included in `openzeppelin-solidity` library?

**Comment by k06a** [comment]
@frangio @nventuro what do you guys think of this line?
```
require(value <= _balances[from]);
```
I am sure this overflow check is already exist in this line:
```
_balances[from] = _balances[from].sub(value);
```
It seems we can save some gas.

**Comment by frangio** [comment]
The redundancy in those lines has come up before, but if you feel we need to revisit the discussion please open a different issue.

`Feeless` is super interesting! I'm interested in providing stuff like that in OpenZeppelin in the future, but I personally don't see it in the roadmap very soon.

Thanks @k06a!

**Comment by ardagokcek** [comment]
Yes, you are true sorry. I was thinking about if someone overrides _transfer and does add some extra controls without any revert only with returning 0. Code is perfect, thank you for describing kindly and for your contribution.

Am 13.10.2018 um 11:24 schrieb Anton Bukov <notifications@github.com<mailto:notifications@github.com>>:


@ardagokcek<https://github.com/ardagokcek> I think changing this lines order will not help in this case. You mean someone overrides _transfer? It should revert in case of failure. I used this order of lines because of order of lines 207-209.

**Pull request merged**
