### PR TITLE
Functions in interfaces changed to "external"

### PR DESCRIPTION
**Pull request by Miraj98**
Fixes #

# 🚀 Description

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by frangio** [comment]
Sweet, thank you @Miraj98!

**Comment by yoheioka** [comment]
May I ask what the reason was behind the changes from `public` to `external` in the ERC20 interface? I find it cleaner if they are kept public.
I'm already running into issues when running static analysis tools like [oyente](https://github.com/melonproject/oyente) (`Error: Overriding function visibility differs`)
because [ERC20.sol](https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC20/ERC20.sol) defines them as `public` rather than `external`

**Comment by nventuro** [comment]
Because `external` is a subset of `public`: our implementation is public to allow derived contracts to make internal calls to the interface functions, but that's an implementation detail and shouldn't affect the interface.

**Comment by yoheioka** [comment]
Thanks for the clarification. I found some context behind this here: https://github.com/ethereum/solidity/issues/2330

**Comment by frangio** [comment]
@yoheioka If you're getting that error there is a bug in Oyente. `external` functions in `interface` contracts can be implemented by `public` functions. It doesn't count as overriding visibility.

**Pull request merged**
