### PR TITLE
Remove underscores from event parameters.

### LINKED ISSUE #1175: Remove underscore from events' arguments
Some of our events have arguments with a leading underscore on their name. This underscore is unnecessary because there is not chance of ambiguity with these arguments, so it should be removed.

### PR DESCRIPTION
**Pull request by elopio**
Fixes #1175

- x ] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by nventuro** [comment]
I only now read the issue, my bad! If @frangio has no issue in removing those then I also don't. We may want to add a comment though in the code style document though, explaining what we're doing.

**Comment by elopio** [comment]
@nventuro there is a comment on CODE_STYLE.md about this. Do you mean something other than that?

**Comment by nventuro** [comment]
I meant about the fact that we're renaming properties from standard specifications.

**Comment by elopio** [comment]
@nventuro I've added an extra comment on CODE_STYLE. How does it look?

**Comment by frangio** [comment]
Thanks!

**Pull request merged**
