### PR TITLE
Feature/multi send

### LINKED ISSUE #704: Add Airdrop contract
- [ ] 🐛 This is a bug report.
- [X] 📈 This is a feature request.

Introduce an Airdrop smart contract standard to the OpenZeppelin library.

Airdrops became a way for projects to distribute tokens to their community, in an effort to bootstrap the usage and support of their platform. During 2017, we've seen Airdrops performed by projects like OmiseGo and Kyber, among others:
https://github.com/omisego/airdrop
https://github.com/KyberNetwork/airdrop
Also, products are emerging for projects to perform Airdrops: https://news.earn.com/launch-your-token-with-an-earn-com-airdrop-97715970f8c7

With an increasing number of emerging projects in the space struggling to get the adoption they need to justify their market prices, I believe Airdrops will become more popular during 2018. Therefore, it would be great to have an Airdrop smart contract standard in OpenZeppelin, the most popular smart contract library in the space today.

### PR DESCRIPTION
**Pull request by AngelicaFulcher**
Fixes #704

# 🚀 Description

MultiSendToken contract allows the transfer of specific amounts to multiple accounts. Implemented as an extra functionality of a StandardToken.

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by SCBuergel** [comment]
@sheluchin I'd suggest using e.g. [`wrapped ETH`](https://weth.io) to multi-send Ether.

The idea here is that you could derive some custom token from this `MultiSendToken` in order to have the functionality, that's something very token-specific.

**Comment by sheluchin** [comment]
I understand the idea here but still think a broader approach would be better. There's obviously a need for a reference multisend contract that people can use. I don't entirely agree that it always needs to be coupled to `StandardToken`, as there may be users who want to multisend many different types of existing ERC20 tokens and there's no reason code like this can't be used generically. 

W-ETH would work but it's somewhat inconvenient for both the sender and the receiver.

https://github.com/Alonski/MultiSendEthereum/blob/master/contracts/MultiSend.sol may be of interest to anyone reading this PR as it handles multisending ERC20 tokens as well as ETH.

In any case, thank you @AngelicaFulcher for posting this PR in the first place.

**Comment by rstormsf** [comment]
mutlisend eth is different than erc20 multisend.
Also, I wouldn't agree multisendToken needs to inherit from StandardToken

Check out similar Dapp:
https://rstormsf.github.io/multisender/#/

**Comment by nventuro** [comment]
Closing due to staleness. I also agree with the statement that a more generic solution would be preferred, since these can be easily added ad-hoc by users when required.

**Pull request closed without merging**
