### PR TITLE
Make ERC721.exists internal

### LINKED ISSUE #1192: clarify that exists() is an extension to ERC-721
This statement is incorrect:

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/DeprecatedERC721.sol#L9

And this is a proprietary extension to ERC-721. 

https://github.com/OpenZeppelin/openzeppelin-solidity/blob/master/contracts/token/ERC721/ERC721BasicToken.sol#L69

Please add a note that the `exists` function is an extension and is not part of the standard. This will help avoid confusion.

### PR DESCRIPTION
**Pull request by nventuro**
Fixes #1192 (see this issue for some relevant discussion).

### CODE REVIEW

**Comment by nventuro** [comment]
Waiting for a second approval, since this is a breaking change.

**Comment by nventuro** [comment]
Can't believe I forgot about that. Go double review policy!

**Comment by frangio** [comment]
Any way we can prevent missing stuff like this in the future? Asking about ER165 interfaces specifically.

**Comment by shrugs** [comment]
@frangio it might be hard to validate that with proxy situations, but I'd support it for the base contracts

**Pull request merged**
