### PR TITLE
Create Unpausable

### PR DESCRIPTION
**Pull request by ProphetDaniel**
Unpausable has a more limited functionality than Pausable smart contract in the sense that it starts paused and leaves room for unpausing the operation once later on.

### CODE REVIEW

**Comment by maraoz** [comment]
I like the idea. Can you make `Pausable` inherit from `Unpausable` and add tests? (should be the same as in `Pausable`) (a subset actually)

**Comment by ProphetDaniel** [comment]
@maraoz , I updated the family of pauseable smart contracts with the following contracts for the `contracts/lifecycle` folder:

1. `PauseInfrastructure`
2. `Unpausable` which is a `PauseInfrastructure` and allows a contract which starts naturally paused to be unpaused once.
3. `Pausable` which is a `PauseInfrastructure` and allows a contract which starts naturally unpaused to be paused once.
4. `PauseUnpauseAble` which is a `PauseInfrastructure` and allows a contract to pause and unpause at will. The initial paused state is set throught the constructor parameter ´_paused´.

Additionally `contracts/token` folder now has:

1. `PausableToken` which is `Pausable` and `StandardToken`
2. `UnpausableToken` which is `Unpausable` and `StandardToken`
3. `PauseUnpauseAbleToken` which is `PauseUnpauseAble` and `StandardToken`

For testing the smart contracts above, `test` folder now has also:

1. `Pausable.js` to test `Pausable.sol`
2. `Unpausable.js` to test `Unpausable.sol`
3. `PauseUnpauseAble.js` to test `PauseUnpauseAble.sol`
4. `PausableToken.js` to test `PausableToken.sol`
5. `UnpausableToken.js` to test `UnpausableToken.sol`
6. `PauseUnpauseAbleToken.js` to test `PauseUnpausableToken.sol`

And test hepers in folder `test/helpers`

1. `PausableMock.sol` to help test `Pausable.js`
2. `UnpausableMock.sol` to help test `Unpausable.js`
3. `PauseUnpauseAbleMock.sol` to help test `PauseUnpauseAble.js`
4. `PausableTokenMock.sol` to help test `PausableToken.js`
5. `UnpausableTokenMock.sol` to help test `UnpausableToken.js`
6. `PauseUnpauseAbleTokenMock.sol` to help test `PauseUnpausableToken.js`

**Comment by federicobond** [comment]
NACK. I find this unnecessarily complex. The deeper and more complex the inheritance hierarchies, the harder it is to follow and audit the execution flow.

Also, and very importantly, now Pausable is a very dangerous contract to inherit from, because it could lock things up forever, with no possibility to unpause; while the rather awkwardly named PauseUnpauseAble is usually what you will want to use.

**Comment by maraoz** [comment]
Agreed. I wouldn't change the semantics of `Pausable` as it exists now. And the name `PauseUnpauseAble` is not very nice. The rest looks good to me.

**Comment by ProphetDaniel** [comment]
>NACK. I find this unnecessarily complex. 

@federicobond , it is less complex actually if you take a look at `Pausable` and `Unpausable` contracts now they implement a smaller functionality than the previous `Pausable` did in the past in a cleaner way. That means more performance and less cost for each specific case, isn't that what you should be looking for?

> The deeper and more complex the inheritance hierarchies, the harder it is to follow and audit the execution flow.

I totally disagree with you. The framework organic growth will naturally increase complexity and inheritance hierarchies, so you should rather focus on robust engineering than fearing necessary complexity growth. There are several strategies to manage complexity like UML class diagrams for the structure, code generators and so on. Still IDE's are not intuitivelly showing the relationship among contracts. But sooner or later they will represent quite well. How to make composition and aggregation associations, instantiation and statemachine diagrams for a smart contract? Even proxy contracts shouldn't be hard to debug and implement. In this regard the ecossystem needs to improve right away, and it is.

> Also, and very importantly, now Pausable is a very dangerous contract to inherit from, because it could lock things up forever, with no possibility to unpause; while the rather awkwardly named PauseUnpauseAble is usually what you will want to use.

OpenZeppelin is a library that should give programmers solutions to whatever they are looking for to implement. I'm pretty sure there are use cases where the intended functionality is to have the possiblity to just pause forever a token for example or like unpausable does to just unpause once. What you have described is user's mistake and OpenZeppelin was never responsible for that.

> awkwardly named PauseUnpauseAble.

If the name is the problem, suggesting another beautiful name makes the job, doesn't it? I mean software structures regardless of the name represent the most important technological feature. Labeling each contract accordingly is advisable for readability purposes.

**Comment by ProphetDaniel** [comment]
How about relabeling?

1. `Pausable` to `PausableOnce`
2. `Unpausable` to `UnpausableOnce`
3. `PauseUnpauseAble` to `Pausable`

**Comment by federicobond** [comment]
If it comes down to names, perhaps a better alternative would be Startable, Stoppable and Pausable.

**Comment by ProphetDaniel** [comment]
@federicobond , looks great!

**Comment by maraoz** [comment]
Agreed in that OpenZeppelin's contracts shouldn't leave much space for user error. The `PausableOnce`/`Stoppable` contract (and it's token versions), where one cannot unpause/resume the contract, doesn't seem very useful and can be confusing. 
I'd remove it from the PR

**Comment by ProphetDaniel** [comment]
Later on today I will remove Stoppable family of contracts and testers.

**Comment by maraoz** [comment]
Please rebase

**Comment by maraoz** [comment]
can you rebase? The commit history in this PR is very messy

**Comment by ProphetDaniel** [comment]
Rebasing several times resulted in the current mess. A clean option would be to clone again and create a new PR.

**Comment by federicobond** [comment]
Use this:

git rebase -i master

And squash every commit into a single one with appropriate message.

**Comment by frangio** [comment]
I appreciated the thoughts on complexity and growth, and I agree with putting the focus on robust engineering. Unfortunately there is no way to pause all of the functionality of a contract without the developers manually placing the correct modifiers on every function, so I feel that the the complexity introduced in this PR is not worth the returns.

Apologies for the delay and thanks @ProphetDaniel!

**Pull request closed without merging**
