### PR TITLE
WIP -- Adds EIP 1337 Style Subscriptions

### PR DESCRIPTION
**Pull request by owocki**
Hi there,

This PR is an extension of a conversation that @frangio and I had at ETHDenver.   I would like to engage the Open Zeppelin team to figure out a roadmap to getting EIP 1337 style subscriptions into Open Zeppelin.

Monthly subscriptions are a key monetization channel for legacy web, and arguably they are the most healthy monetization channel for businesses on the legacy web (especially when compared to ad/surveillance) based models. They are arguably more healthy than a token based economic system (depending upon the vesting model of the ICO).

For these reasons, I think it's worth talking about the viability of creating a standard way to do 'subscriptions' on Ethereum.   Getting distribution via OZ for this pattern would be huge for the business models of dApps in the space.

This contract was built for [Gitcoin Grants](https://gitcoin.co/grants), and is built upon the [EIP 1337](https://1337alliance.org) standard.

Specifically, it is built upon [this smart contract](https://github.com/gitcoinco/grants1337/blob/master/contracts/Subscription.sol) which [was audit'ed by ZKLabs in Q4 2018](https://hackmd.io/s/HJ1QgH8F7).

To learn more about how we architected this, solution, see [this architecture deep dive](https://medium.com/gitcoin/technical-deep-dive-architecture-choices-for-subscriptions-on-the-blockchain-erc948-5fae89cabc7a) and [EIP 1337 itself](https://github.com/ethereum/EIPs/pull/1337) and its predecessor, [ERC 948](https://github.com/ethereum/EIPs/issues/948)

Obviously, this is not yet complete per the OZ contributor guidelines.  That said, I am committed to getting it over the finish line.  Some TODOs to get it there:

TODOS
* [ ] Adds tests of the functionality
* [ ] Add documentation on how the Subscription Contracts are architected.
* [ ] run the JS/Solidity linters and fixed any issues (`npm run lint:fix`), and
* [ ] updated the changelog, if applicable.

Credit to @austintgriffith for building the original smart contracts and @captnseagraves for his work on Gitcoin Grants.  Also the Gitcoin team @thelostone-mc @saptakS @octavioamu for their help building the Gitcoin Grants product.

### CODE REVIEW

**Comment by androolloyd** [comment]
Would love to see this happen, here to help. Groundhog is in the audit phase of its 1337 implementation, and are looking to deploy the next iteration to mainnet this week.

**Comment by nventuro** [comment]
Hey there @owocki, thanks for opening this!

What's the current status of the 1337 EIP? It looks like a PR was opened back in August, with no updates since October, despite multiple comments from prominent community members.

**Comment by androolloyd** [comment]
@nventuro there will be an update coming this week based on some community feedback.

**Comment by nventuro** [comment]
Hello! There still seems to be no activity whatsoever on the EIP, is anybody still working on this?

**Comment by nventuro** [comment]
Closing due to staleness of both this PR and the EIP.

**Comment by frangio** [comment]
We'll keep an eye on the EIP and possibly revisit this PR later.

**Comment by androolloyd** [comment]
There is still active work on the EIP, a new implementation published [(here)](https://github.com/groundhognetwork/smart-wallet), feature/mainnet branch

**Comment by Aeroxander** [comment]
EIP has been merged :D https://github.com/ethereum/EIPs/pull/1337 https://github.com/ethereum/EIPs/pull/2789

**Comment by frangio** [comment]
Awesome that it has been merged. We will still want to wait until the EIP is Final to publish an implementation, but we can begin working on it once it's heading to Final.

**Pull request closed without merging**
