### PR TITLE
WIP: Timed payments

### PR DESCRIPTION
**Pull request by currymj**
Providing code to perform actions per interval.

Specific implementation is code to asynchronously pay an address as the block timestamp increases. But I envision this being pretty generic -- you could watch the block number increase instead, or even watch some quantity in an oracle contract somewhere, and perform any action, not just payment.

This is definitely a work in progress. There is much more to be written. In particular, I definitely need to write tests. But, I have no idea how to test this behavior -- how do you tell the testing framework to mine some more blocks so that we can see time pass? I think it's better to get feedback early than late.

### CODE REVIEW

**Comment by maraoz** [comment]
I really like the code style, and how you used `PullPayment`. In general, I like where this is going, and how you abstracted the contracts.
Related: https://github.com/OpenZeppelin/zeppelin-solidity/issues/23

As for testing "time-traveling", I hear test-rpc 3.0.0 has a lot of nice features. Not sure how to exactly do this because I haven't played much with it myself. Maybe someone else can give you better info on that. 

Minor ask for next time: if the PR is not intended for merge, prepend "WIP" to the title. I'm assuming it's not intended from your "This is definitely a work in progress.", but given Zeppelin is very new still, I'm OK with merging preliminary/untested code for now, so let me know :)

**Comment by maraoz** [comment]
@currymj any updates on this? need help with something? I'd love to merge this to Zeppelin :)

**Comment by currymj** [comment]
No updates right now, I just haven't gotten around to it. Planning to make more progress this weekend. Adding a contract that ticks on block number instead of timestamp should be easy (important because miners can game the timestamp).

It seems like integrating https://github.com/DigixGlobal/tempo into the tests would make sense. If this turns out to be painful I will make sure to at least push some simpler tests.

**Comment by maraoz** [comment]
@currymj any updates on this? Would love to include it in zeppelin's v1.0.0 release if you have some time to warp it up :)

**Comment by maraoz** [comment]
@currymj would you like to revisit this PR?

**Comment by maraoz** [comment]
We now have this time helper for tests: https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/test/helpers/timer.js

**Comment by currymj** [comment]
life has gotten pretty busy -- i think I will pick this up again but progress will likely be fairly slow. happy to cede priority if someone else comes along. (sorry for not responding sooner -- i never saw the notification and just came back here after seeing the post on HN).

**Comment by frangio** [comment]
The codebase has advanced quite a bit since this PR :slightly_smiling_face: so it can't be merged as-is. I'm going to close it because we have quite a bit on our plate and the need for the feature hasn't come up.

**Pull request closed without merging**
