### PR TITLE
Safer version of StandardToken. Fix #442

### LINKED ISSUE #442: Create a subcontract of StandardToken that rejects holding funds
A subcontract of StandardToken.sol which also implements HasNoEther and HasNoTokens.
This would prevent token contracts from holding unclaimable ETH or token balances, which happens a lot by user error. 

Idea suggested by @SergioDemianLerner

### PR DESCRIPTION
**Pull request by SylTi**
I found it difficult to find a good name for it. If you have suggestions... 👍

### CODE REVIEW

**Comment by ajsantander** [comment]
I agree that SaferStandardToken sounds a bit generic.
Alternatives: NonHoldingStandardToken? It's actually hard to think of other alternatives.
If we really want this feature to be widely adopted, I think that this feature should be native to StandardToken and having it inherit from a StandardTokenBase that doesn't have the limitation of not being able to hold stuff.

**Comment by AugustoL** [comment]
I would changed the StandardToken instead of adding another version of it, IMO if it is safer and does not change the capabilities/behavior of the StandardToken it should be consider as the standard version.

**Comment by Shrugs** [comment]
Also down to put this in `StandardToken` and a breaking change. People like Request Network have already added this functionality themselves ad-hoc.

**Comment by nventuro** [comment]
Closing as stale.

**Pull request closed without merging**
