### PR TITLE
Implement partial refunds in CappedCrowdsale.

### PR DESCRIPTION
**Pull request by alcuadrado**
This PR modifies the behaviour of CappedCrowdsale when a transaction whose value is larger than the amount needed to reach the cap. Now CappedCrowdsale accepts just enough to reach the cap, and refunds the rest.

### CODE REVIEW

**Comment by martriay** [comment]
@alcuadrado Interesting! What about a sender who only wants the exact amount who tried to buy?

**Comment by ajsantander** [comment]
@ping alcuadrado?

**Comment by alcuadrado** [comment]
@martriay The semantic of this operation is changed to "buy tokens up-to X wei". 

There are multiple reasons why I think this change is a good thing:

1. I think it's more aligned with what most users want to do, specially the ones trying to buy the last few tokens.

2. This makes the crowdsale's operations simpler, as there's no need to try and send an exact amount of wei to close  it. 

3. Depending on the client being used to buy the tokens, closing the crowdsale ASAP can save the buyer's gas, as the clients' UI can be updated earlier to reflect the fact that no purchase will be accepted.

**Comment by ajsantander** [comment]
@alcuadrado I love the idea but I don't like the implementation very much =/
Besides, this PR is out of sync with the refactor we are doing to crowdsales #744. It would be awesome if you could revisit this and implement in `CappedCrowdsale`.

**Comment by alcuadrado** [comment]
@ajsantander I don't like this implementation either. I think it would be better to close this PR and reimplement it after #744 gets merged, as that PR it's pretty much an overhaul of everything crowdsale.

**Comment by nventuro** [comment]
Closing as stale. It is however still true that the last purchasers will need to not go over the cap to prevent triggering a revert.

**Pull request closed without merging**
