### PR TITLE
Add/feature #1602

### PR DESCRIPTION
**Pull request by ryachen01**
Fixes #

Made Roles iterable as described in issue #1602

### CODE REVIEW

**Comment by elopio** [comment]
Thanks @ryachen01! Please give us some time, we'll review it next week.

In the meantime, can you please add the unit tests? Take a look at the coveralls failure report.

**Comment by ryachen01** [comment]
@elopio Hi! Do you think you could review my PR sometime soon?

**Comment by elopio** [comment]
Hello @ryachen01. Sorry it's taking long to review it. Please give the maintainers some time while they catch up with the queue.

**Comment by nventuro** [comment]
Hello @ryachen01, thanks for contributing to OpenZeppelin!

I fear you may have misunderstood the idea behind #1602, what we want to do is not create a new role such that accounts with that role can be enumerated, but rather improve `Roles.sol` so that _all_ roles have a mechanism to do this, if required. There's even some discussion in that issue related to what would be the best approach to do this, data-structure wise.

Closing this issue.

**Pull request closed without merging**
