### PR TITLE
Implemented DuctionAuction contract for NFTs and corresponding unit tests

### LINKED ISSUE #458: Add auction contract
Auctioning non-fungible assets is a common requirement for smart contracts (an example even appears in the [Solidity docs](http://solidity.readthedocs.io/en/latest/solidity-by-example.html#blind-auction). It would be great if OpenZeppelin included a standard auction contract for use with either ERC20 tokens or Ether.

### PR DESCRIPTION
**Pull request by dougiebuckets**
Fixes #458. Worth noting, we weren't entirely sure where an auction contract should reside in OpenZeppelin's current file structure. We went ahead and created an 'auctions' directory in 'contracts' and 'tests' as we intend to build additional auction style contracts as there are many different types of auctions. Happy to reorganize depending on what the maintainers feel is best.

# 🚀 Description

DutchAuction is a contract for managing the dutch auction of a non-fungible token (NFT). 
 The contract owner, or beneficiary, sets their high asking price and their low, reserve price for the NFT they are auctioning off. Additionally, the beneficiary sets the length of time for which they'd like their auction to run.

To start the auction the beneficiary calls the startAuction function and passes it the token's contract as well as the tokenId of the NFT they are auctioning. The asking price for the NFT decreases every day at a rate that is proportional to the total amount of time between the high asking price and the low, reserve price. E.g., (highAskingPrice - lowAskingPrice) / auctionLength = descendingPriceRate

The first bidder to bid on the NFT's currentAskingPrice is awarded the NFT.

This has also been called a clock auction or open-outcry descending-price auction. This type of auction is good for auctioning goods quickly, since a sale never requires more than one bid. 

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by dougiebuckets** [comment]
I went ahead and loaded all of the test accounts w/ 15000 ETH `ganache-cli -e 15000` ran all of the unit tests, and they all passed locally.  Anything I can do to this PR to get Coveralls to green light it?

**Comment by gnoblin** [comment]
so what's the current status of auctions in OZ? Thanks

**Comment by dougiebuckets** [comment]
@gnoblin This was our first contribution to OZ and it's evident to us now that the auction contract we submitted in this PR is much too clunky and trying to do too much. CC'ing @kseniya292

That said, much of the code in this PR could be used to create an abstraction layer that would be more modular and better suited for the OZ codebase. @nventuro, @shrugs - Would you guys agree w/ that?
 
@gnoblin - In the meantime, if you're looking to implement your own custom auction contract, don't hesitate to reach out.

**Comment by gnoblin** [comment]
Hi! In general, is there any specific reason this Dutch auction spawns a new contract for each lot and doesn't hold a registry of auctions going on like in https://github.com/satansdeer/gradient-token-tutorial/blob/master/contracts/TokenAuction.sol ? Thanks

**Comment by nventuro** [comment]
Considering progress hasn't advanced on this front, users of auctions may want to take a look at Gnosis's DutchX: https://blog.gnosis.pm/new-dutchx-smart-contracts-are-now-live-665d83f31930

Closing due to staleness.

**Comment by dougiebuckets** [comment]
@nventuro Thanks for sharing Gnosis's DutchX. Very cool :)

**Pull request closed without merging**
