### PR TITLE
Make IERC721 an interface as per the spec.

### PR DESCRIPTION
**Pull request by nventuro**
Fixes https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1679. Thanks @Aniket-Engg for the suggestion!

### CODE REVIEW

**Comment by frangio** [comment]
This is a breaking change for abstract contracts like the following.

```
contract ERC721ReceiverExtension is IERC721Receiver {
    function foo() public {
        onERC721Received(...);
    }
}
```

It's unlikely that someone would write a contract like this, though, so I think I'm comfortable with introducing this change in a minor version. What do you think?

**Comment by nventuro** [comment]
Hm, I hand't considered that. Putting on hold until the next major release then.

**Comment by frangio** [comment]
Accidentally marked `stale`. See https://github.com/OpenZeppelin/openzeppelin-solidity/commit/59f03f00c5d04c5daaeab7f9c4e49ee1a0656536.

**Comment by frangio** [comment]
Closing in order to delete the branch in this repository.

**Pull request closed without merging**
