### PR TITLE
Add tokensOf function to return a list of tokens

### PR DESCRIPTION
**Pull request by kookiekrak**
# 🚀 Description
This re-adds the tokensOf function onto ERC721Token.sol so that you can query the contract for all tokens owned by an owner address.

The same result is otherwise achievable by querying the balanceOf(OWNER) and then enumerating each index tokenOfOwnerByIndex(OWNER, INDEX), which is computationally expensive.

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](/docs/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by okwme** [comment]
Token indexes should not be expected to be in incrementing order. Having a better way to return all tokens of a certain address would be really helpful in a lot of scenarios.

**Comment by leanthebean** [comment]
I agree - I just re-implement this every time I make a new ERC721 contract now. Does anyone know what was the rationale in deleting this method to begin with?

**Comment by nventuro** [comment]
Looks like it was removed from [the standard](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md) and therefore from the code. I agree that it's a nice utility though. @shrugs you're more familiar with the whole NFT scene, do you have any thoughts on this?

**Comment by shrugs** [comment]
just a clarification, @okwme; token _ids_ need not be incremental at all; The token ids themselves are arbitrary, but their _index_ in the array of an owners tokens are guaranteed to be incremental.

Anyway, this function is a foot-gun. It enables you to write quick-and-dirty code that will not scale past a certain point (whatever the maximum return size of a dynamic array of  uin256 in solidity is). 

This means it's a double edged sword; you can use this function to easily get an array of an owner's tokens, but it will eventually break and therefore shouldn't be depended on for production-ready applications.

The pseduo for constructing an array of a user's token ids looks like

```
const numberOfTokens = await token.balanceOf(owner)
const tokens = asyncMap([0...numberOfTokens], (i) =>
  await token.tokenOfOwnerByIndex(owner, i)
)
```

Which is guaranteed to not break in the future, although it will probably be slower if you don't batch your requests to your web3 instance.

Anyway, the point is that `tokensOf` is a short-term crutch.

I support making it an optional mixin for ERC721Token, complete with its own ERC165 identifier like `InterfaceId_ERC721TokensOf`. It should not be included by default, and the comment above the function should re-iterate what we've talked about here and how it's a shortcut that will _eventually_ break and the author of the contract must be ok with that.

**Comment by nventuro** [comment]
That's a great point regarding scalability (I wonder if that's what got it removed from the standard?). 

I don't feel comfortable adding a shortcut we know will break, not in an immutable code context, and specially considering it's not even part of the standard.

**Comment by nventuro** [comment]
I'm siding with 1), but think we should have a clear stance regarding this. @frangio WDYT?

**Comment by shrugs** [comment]
JSON-RPC batching is generally _fine_ in terms of removing the `n` round-trips, but isn't as fast as a solution as a real off-chain index via something like gnarly.

I went to go document what a batch request In web3-1.0.0 would look like, but realized that batch requests are very poorly document and highly under-served in web3.

```js
const owner = '0x0'

var batch = new web3.BatchRequest();
const balance = await token.methods.balanceOf(owner).call()
for (let i =; i < balance; i++) {
  batch.add(token.methods. tokenOfOwnerByIndex(owner, i).call.request(
    (err, result) => { // somehow collect all of the results into an array }
  ));
}
batch.execute();
// ^ this doesn't return a promise (???????????) so it's impossible to know when it's done without, like, just counting the number of times your callbacks are executed and checking to see if that matches
```

anyway, batch requests in web3 are officially "annoying" to work with, so I can definitely see an argument for what's effectively adding that functionality to the smart contract you're querying.

**Comment by frangio** [comment]
Huh, that sucks. To be fair though this doesn't sound like the use case that batch requests were designed for.

What if the list of owned tokens was paginated? The contract could return a list of the first _n_ tokens and, if there are more available, the next _n_ can be queried (with some way to detect race conditions). Does anyone know if this was considered for ERC721? It makes a lot of sense, and databases have done it this way for a long time so why not. I guess `tokenOfOwnerByIndex` is pagination with _n = 1_. It would be interesting if the _n_ was an argument, you could scale it with the blockchain.

We could implement such non-standard pagination in OpenZeppelin, but this is the kind of thing that should probably be discussed in an ERC context first. @shrugs perhaps you can gather some opinions on this at NIFTY?

Of course you can also use events to reconstruct the array and I used to be quite into that but I'm not so sure any more. It's probably too wasteful of the end-user's resources.

**Comment by shrugs** [comment]
I'm wary of supporting any sort of query information that is not minimum-viable; smart contracts aren't really designed to be postgres.

What could also work is a proxy contract that implements that pagination on top of an existing ERC721 without its permission aka

```
contract 721Querier {
  ERC721Token public token;
  constructor (ERC721Token _token) public { token = _token }

  function tokensOf(address _owner) external view returns (uint256[])
  {
    uint256 balance = token.balanceOf(owner);
    uint256[balance] memory tokenIds;
    
    for (...) {
      tokenIds[i] = token.tokenOfOwnerByIndex(owner, i)
    }

    return tokenIds;
  }
}
```

likewise for pagination

**Comment by frangio** [comment]
(Sorry, I was too quick to mark `on hold`.)

Right! And you don't even have to deploy that code. You can embed it in an `eth_call`! I don't remember seeing a high-level way to do that though.

**Comment by kookiekrak** [comment]
@shrugs problem with those iterative implementations is that they burn through a ton of gas when used.

**Comment by nventuro** [comment]
I think we're way past the point of code review: I'd close this PR and open a research issue on how to tackle these sort of unbounded array queries, discussing solutions such as [gnarly](https://github.com/XLNT/gnarly), the `eth_call` query, etc.

**Pull request closed without merging**
