### PR TITLE
[WIP] ERC20Buyer

### PR DESCRIPTION
**Pull request by SylTi**
- [ ] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](/docs/CONTRIBUTING.md)
- [ ] ✅ I've added tests where applicable to test my new functionality.
- [ ] 📖 I've made sure that my contracts are well-documented.
- [ ] 🎨 I've run the JavaScript linter (`npm run lint:fix`) and fixed all issues.

Fixes #

---

# 🚀 Description
This is a Work in Progress, it's not intended to be merged right now.
I'm simply looking for feedback on this so any would be appreciated! :)

The purpose of this contract is to allow users to pool funds in advance before the start of a Crowdsale into a single contract executable by anyone at the time of the sales. 

Advantages : 
- only a single user needs to be available at the time of the sale (or could be run later by OZ OS scheduler)
- This can help reduce network load in time of high congestion
- Lower gas consumption for participant overall

### CODE REVIEW

**Comment by spalladino** [comment]
Looks good @SylTi! A few comments:

- Why is it that there is lower gas consumption per participant overall? The way I see it, each participant needs to make a transfer to the Buyer contract, and then another transaction to claim the tokens, which I'm not sure would take less gas than a single buyTokens call to the crowdsale contract.

- Make sure to add a way to claim the funds if the purchase is unsuccessful, otherways all pooled ETH may be left stuck in the buyer contract.

- The fact that the contract is public and has no bounds or caps makes me a bit nervous, though I'm not sure why. Perhaps adding a whitelist of participants as an extension?

**Comment by SylTi** [comment]
Hey @spalladino thanks for the feedback!

- My assumption about the gas consumption was that people set a much higher gasPrice when buying into a Crowdsale when here they can put the contract up several days before the crowdsale start and put fund into the contract when the gasPrice is the lowest.

- Funds can be retrieved through the `withdrawPayments()` from `PullPayment.sol` at any point as long as the funds are still there, otherwise, it will fail since the contract balance would be empty

- I like that idea, but maybe on a child contract? A bounty could also be added, as a reward,  for the caller of `execute()` function.

**Comment by spalladino** [comment]
- Got it, I was thinking about gas usage, not price, which is indeed higher in first-come-first-serve capped crowdsales.
- Completely missed the PullPayment, my bad!
- Agree, a child contract may be better for it.

**Comment by SylTi** [comment]
@spalladino Is this a type of contract you would want to merge at some point? 
If it is let me know so I can rework it & add some tests, otherwise maybe we should close the PR?

**Comment by nventuro** [comment]
Closing due to staleness.

**Pull request closed without merging**
