### PR TITLE
Making visibility explicit for storage variables

### PR DESCRIPTION
**Pull request by redsquirrel**
# 🚀 Making `balances` and `totalSupply_` visibility explicitly public in BasicToken

They are currently implicitly public.

I assume that `totalSupply_` could have originally been made private, since a `totalSupply()` getter was manually created. But it is already public and should stay that way.

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](/docs/CONTRIBUTING.md)
- [ ] ✅ I've added tests where applicable to test my new functionality.
- [ ] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by facuspagnuolo** [comment]
I think it make sense setting them as private variables instead

**Comment by Shrugs** [comment]
I support private for `totalSupply_` but I'd avoid changing the typesig of `balances` for backwards compatibility.

**Comment by redsquirrel** [comment]
Making `totalSupply_` private  seems aggressive. If it's not public, it should be make internal. Otherwise how would people set the `totalSupply_`? But why not just keep them public as they already are?

**Comment by Shrugs** [comment]
`internal` for `totalSupply_`, sorry, good catch, redsquirrel

@facuspagnuolo is `internal` for totalSupply and an explicit `public` for balances good?

**Comment by k06a** [comment]
If we are talking about explicitness, then both should be made `internal` as they currently are.

**Pull request merged**
