### PR TITLE
erc721 mintable and bouncer updates

### LINKED ISSUE #962: RBAC with owner
## 🎉 Description

- [ ] 🐛 This is a bug report.
- [x] 📈 This is a feature request.

## 📝 Details

`Ownable` controls ownership of contract. I think `RBACWithOwner` is suitable to control access controll with permission than `RBACWithAdmin`. `RBACWithAdmin` has several problems.

1. It can't be integrated with `Ownable` becuase both control permissions. If we have a contract `T is RBACWithAdmin, Ownable` and a single `admin` added, and want to chagne `owner`, 3 transaction are required
```javascript
contract.transferOwnership(newOwner, {from: owner});
contract.adminAddRole(newOwner, 'admin', {from: owner});
contract.adminRemoveRole(owner, 'admin', {from: owner});
```

2. `RBACWithAdmin` may have no `admin` at all if `admin` send trancation
```javascript
contract.adminRemoveRole(admin, 'admin', {from: admin});
```

I suggest to integrate `Ownable` with `RBACWithAdmin` to handle `owner` and `ROLE_ADMIN` at the same time, making sure that `owner` has all permission to control `ROLE_ADMIN`

### PR DESCRIPTION
**Pull request by shrugs**
Supercedes #957 and #950 

fixes #962

# 🚀 Description

cc @vittominacori for review

- `DefaultTokenURI.sol` — implement `tokenURI(uint256 _tokenId)` and returns a default `tokenURI` if a specific token URI is not set. saves the developer from storing the same tokenURI for every token
- `RBACMintable.sol` — a super simple mintable role with `onlyMinter` modifier. Does not suggest role authorization, which is left up to the implementer. Pairs well with `RBACOwnable`
- `RBACOwnable` — an `Ownable` implementation that allows multiple owners that can add/remove themselves
- `MintableERC721Token.sol` — an `ERC721Token` that can be minted by anyone with the `minter` role.
- `ERC721Burnable` — an interface to support `burnFrom()` mechanism
- `BurnableERC721Token` — an implementation of that interface

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by vittominacori** [comment]
@shrugs pushed in your repo 

https://github.com/shrugs/zeppelin-solidity/pull/1

It should solve test failing.

**Comment by frangio** [comment]
I see a few problems with this PR.

It's very complex, and doesn't feel very cohesive. There's additions to our ERC721 stack, SignatureBouncer and RBAC, as well as new stuff like `NonceTracker` and `AutoIncrementing`. It's very hard to review such disparate components. The huge new context in which they are presented results in a lot of overhead. We should aim for more cohesive and as small as possible PRs. I believe this will lead to better reviews by making better use of our time and focus. (In the possible case that a huge feature has to be developed, it should probably be done in an ongoing `in progress` PR with incremental reviews from the same reviewer.)

Additionally, I'm not quite convinced that `ERC721Minter` should be a part of OpenZeppelin. Although `SignatureBouncer` is very interesting, we shouldn't start writing bouncers for every feature in the library. `ERC721Minter` is a fine _example_ of how a developer might build a system by composing a `MintableERC721Token` with a `SignatureBouncer`. What we should aim for is designing, writing, and documenting building blocks that can be safely composed by developers with little code. `ERC721Minter` is a success in this sense: it is very little code doing something quite powerful built out of OpenZeppelin components, but it is not something that I would include in the library.

What do you think about this?

My concrete proposal is to continue work on #957, and then merge `ERC721Minter` only as an example (i.e. in the `examples/` directory).

**Comment by shrugs** [comment]
@frangio Keeping ERC721Minter inside examples is good 👍 

This PR is super huge, and it totally is all over the place, yeah. With the removal of ERC721Minter we can split noncetracker, autoincrementing, and signature bouncer changes into separate PRs. Will do that unless you have extra thoughts.

**Comment by shrugs** [comment]
@frangio thanks for the feedback, I feel a lot better about the PR now. split them into

https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1022
https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1023
https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1024

**Comment by nventuro** [comment]
@shrugs should we close this one then, since work continued on those other 3 PRs?

**Comment by shrugs** [comment]
@nventuro this PR will have to eventually be rebased on master once those commits are merged

**Comment by shrugs** [comment]
closing in favor of tracking via https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1272

**Pull request closed without merging**
