### PR TITLE
Add a simple wrapper for address.

### LINKED ISSUE #1771: Address.toPayable()
**🧐 Motivation**
As seen in [this StackOverflow question](https://stackoverflow.com/questions/56154982/call-to-super-owner-transfermsg-value-giving-errors), there's no easy (reasonable) way to convert an `address` into an `address payable`. This was confirmed by the Solidity team on gitter. We should provide a simple wrapper for this ugly conversion.

**📝 Details**
This would simply be a new `internal pure` function in `Address`, that takes an `address` and returns `address payable`. In order to do the conversion, we must first cast the address type into `uint160`.

### PR DESCRIPTION
**Pull request by Skyge**
Fix #1771.

### CODE REVIEW

**Comment by Skyge** [comment]
It seems like I should add test example at `test/utils/Address.test.js`.

**Comment by nventuro** [comment]
Hello @Skyge, thank you for this contribution!

Yes, we should add this in `AddresMock` to test it, and have tests that:

1. convert the zero address
2. convert some random address
3. convert an address of all ones (0xffff...)

All three tests should check that the input address matches the output.

**Comment by Skyge** [comment]
Hi, @nventuro , do you mean `mocks/AddressImpl.sol`? because I did not fine a file named `AddresMock `.

**Comment by nventuro** [comment]
Yes, my bad. Some of the mocks are inconsistently named.

**Comment by Skyge** [comment]
@nventuro Hi, I have thought for the test case for some time, so my process will be like this: First I need a simple contract which can receive Ether, then I use an account to call a function mainly including `address(A).transfer(100)`, because the account is not the type of `payable`, it will throw out an error message, then if I call another function mainly including `address(A).toPayable().transfer(100)`, it will pass, and the balance of account A should add 100.
Same approach for testing the `address(0)` and ` address(0xffff...)`, so what do you think about it? Or I should take another approach to test?

**Comment by nventuro** [comment]
I don't think you'll need to do any of that, because the `payable` attribute is only something the compiler uses to make developers aware of which addresses may receive funds, it's not a property of the address itself.

A function that receives an address, calls `toPayable()` on it and returns it, and checks that the sent and received addresses are the same should be enough.

**Comment by Skyge** [comment]
Emmm, but if I send an address to such a function, it returns an address, how can I know it is a really `address payable`?

**Comment by Skyge** [comment]
@nventuro I notice there is a constant in the `openzeppelin-test-helpers`: `ZERO_ADDRESS`, it is convenient for us to quote, but just like your advice, I also should test for the address of all ones, so is there a necessary to add such constant in the `openzeppelin-test-helpers`, and what should I name it better?

**Comment by nventuro** [comment]
>Emmm, but if I send an address to such a function, it returns an address, how can I know it is a really address payable?

`payable` is a compile-time attribute. The fact that the returned type is `payable` and the contract compiles is enough: all we need to actually test this function is to check that the actual value (the address) is not being accidentally modified.

>I also should test for the address of all ones, so is there a necessary to add such constant in the openzeppelin-test-helpers, and what should I name it better?

I don't think this is necessary, since using this address is very uncommon: I'd just use the `'0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'` string directly.

**Comment by Skyge** [comment]
> I don't think this is necessary, since using this address is very uncommon: I'd just use the '0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF' string directly.

You can see at the line 7, I define a constant: `ALL_ONES_ADDRESS = '0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF'`, it is neither `0xffffffffffffffffffffffffffffffffffffffff`,nor `0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF`, it is a change for address to check whether it is valid or not. Besides, it still does not pass.

**Comment by Skyge** [comment]
It is my pleasure!

**Pull request merged**
