### PR TITLE
Make Truffle provider creation lazy

### LINKED ISSUE #1340: Figure out why the test suite doesn't finish
For some time now we've had hangs in the CI, where the build fails because it goes over the maximum time limit, which requires a manual restart. It also sometimes happens locally. @shrugs [suggested](https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1323#issuecomment-420790968) using  https://github.com/mafintosh/why-is-node-running to find the root cause.

### LINKED ISSUE #1516: truffle compile doesn't exit
`truffle compile` doesn't exit. This is blocking #1299 and #1103.

We have to look into why this is happening and fix it.

### PR DESCRIPTION
**Pull request by frangio**
Fixes #1516
Fixes #1340

It seems like the creation of an `HDWalletProvider` object was blocking Truffle from exiting. I'm guessing this was because of some pending promise, probably related to a network connection that is started. This was completely unnecessary for the general use case of compiling or running the tests against Ganache, so I made the creation of this provider lazy using a JavaScript getter as seen [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get#Smart_self-overwriting_lazy_getters).

To be honest, I haven't tested the provider defined in this way. :-) I just know that it fixes the problem we were having.

### CODE REVIEW

**Comment by spalladino** [comment]
@frangio note that you can assign a function that returns the provider to the `provider` entry in the truffle config file, there is no need to create a custom getter. However, keep in mind that this may cause issues with nonce subproviders if you are using the hdwallet provider (see https://github.com/trufflesuite/truffle-hdwallet-provider/issues/65).

**Comment by frangio** [comment]
@spalladino Oh cool! Thanks, I'll use that feature.

**Comment by nventuro** [comment]
Yay, it works! From my local testing this also seems to fix https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1340. How did you figure it out?

Regarding the fix, do we actually need to have the ropsten network defined? I'd remove the whole thing and drop the `truffle-hdwallet-provider` dependency, though it may be required for some obscure feature that I'm unaware of.

**Comment by frangio** [comment]
Do we need any network other than ganache? I think we used them for EthPM deployment, but that wan't working anyway (though it may be fixable by now, see #824).

**Comment by frangio** [comment]
If you're sure that it fixes #1340 feel free to add the `Fixes` annotation to the description, but I don't have the context for that other issue.

**Comment by nventuro** [comment]
In that case I'd remove the ropsten config, and add it back when (if) the fix the EthPM issue, or any other issue that requires it.

**Comment by frangio** [comment]
Also removed the `ganache` network which was identical to `development`.

**Comment by frangio** [comment]
Seems so!

**Comment by nventuro** [comment]
Looks like we have an implicit dependency on `ethereumjs-util`, can you explicitly install it?

**Pull request merged**
