### PR TITLE
add Searchable contract

### PR DESCRIPTION
**Pull request by jason00111**
# 🚀 Description

Developers can use this Searchable contract to allow contract owners to associate search terms with their contract in a standardized way. Terms are stored as labels in logs, allowing for convenient searching from off chain.

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](/docs/CONTRIBUTING.md)
- [ ] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by Shrugs** [comment]
Can you talk more about how this could be used? I'm not sure what the advantage of a general solution would be — are there websites that would index these events so you could search for smart contracts somehow?

**Comment by jason00111** [comment]
The EVM's logs index these events.  A front end website (no server) can search all past "AddSearchTerm(string)" events to find all contracts associated with a search term.

This allows fully decentralized searching of contracts.

A general solution sets a standard.  If adopted, it provides the value of consensus.  Contracts which use the standard will be more easily discoverable than those which don't.

The next thing to add would be a contract description or message stored in the data part of the logs.

Any feedback is more than welcome!

**Comment by cchx0000** [comment]
@Shrugs @jason00111 I was thinking this could be part of a decentralized DApp store, with appropriate voting governance. The search functionality will allow us to mark out which contracts belong to which DApp.

**Comment by Shrugs** [comment]
Ok yeah I like this a lot now. Would it be reasonable to use something like interface detection to see what keywords a contract supports? We probably also want to consider something around languages, perhaps. Maybe the keywords are `en:exchange` or `jp:koukan` or something like that? 

This issue  could perhaps also be solved by a universal ENS-esq registry of concept -> contracts that are related to that concept. But not storing this info in state is actually pretty useful. 

Perhaps it's best to have a single contract called `ContractSearcher` or something that supports this interface. Then any contract (or account, I guess?) could update its own search terms by calling these functions/events on that ContractSearcher contract. So now we have a centralized place (that anyone can use) to look for contracts that match a search term, instead of having to check every single contract on the network for this info.

This is basically ERC735ClaimManager, but with events, which is pretty neat.

**Comment by cchx0000** [comment]
@Shrugs @jason00111 A registry contract combined with event logs might indeed be the way to go.

**Comment by nventuro** [comment]
Closing due to staleness.

**Pull request closed without merging**
