### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by shrugs**
# Description

Adds the contributor covenant to our open source project!

### CODE REVIEW

**Comment by frangio** [comment]
Not sure why but this one is slightly different than the one found at the [site](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html).

Can we use that one verbatim?

**Comment by shrugs** [comment]
@frangio which parts stand out to you? I don't see it after a quick eyeball

**Comment by nventuro** [comment]
@shrugs yours is missing this section:

> Project maintainers who do not follow or enforce the Code of Conduct in good faith may face temporary or permanent repercussions as determined by other members of the project's leadership.

and says

> regardless of age, body size, disability, ethnicity, gender identity and expression, level of experience, nationality, personal appearance, race, religion, or sexual identity and orientation.

instead of 

> regardless of age, body size, disability, ethnicity, sex characteristics, gender identity and expression, level of experience, education, socio-economic status, nationality, personal appearance, race, religion, or sexual identity and orientation.

**Comment by shrugs** [comment]
gotcha! I'll manually copy and paste the md file from the website instead of using github's interface

**Comment by shrugs** [comment]
is the merge button broken for y'all as well? all green but "required status must pass before merging"

**Comment by frangio** [comment]
Broke for me too :cry:.

I'll force merge it.

**Pull request merged**
