### PR TITLE
style: use the max-len solidity rule

### PR DESCRIPTION
**Pull request by elopio**
This was discussed in https://github.com/ZeppelinSolutions/code-style/issues/3

# 🚀 Description

This updates all the code lines to be shorter than 80 characters.

- [x] 📘 I've reviewed the [OpenZeppelin Contributor Guidelines](../blob/master/CONTRIBUTING.md)
- [x] ✅ I've added tests where applicable to test my new functionality.
- [x] 📖 I've made sure that my contracts are well-documented.
- [x] 🎨 I've run the JS/Solidity linters and fixed any issues (`npm run lint:all:fix`).

### CODE REVIEW

**Comment by frangio** [comment]
I think this should be a warning rather than an error.

**Comment by frangio** [comment]
That's a good point.

My thinking was that the line limit in particular is one that should be enforced "softly". There are scenarios where one can judiciously choose to go over the limit.

Additionally, I don't want contributors' PRs failing because they went over the line limit by two characters.

Let's repoen https://github.com/ZeppelinSolutions/code-style/issues/3 and discuss there.

**Comment by elopio** [comment]
@frangio so let's land this with a warning, and keep going with the discussion on the code-style branch.
Thanks for the review!

**Comment by elopio** [comment]
ok, merging for now as a warning. Anybody with opinions, please leave them here: https://github.com/ZeppelinSolutions/code-style/issues/6

**Pull request merged**
