### PR TITLE
Adding canBuyTokens / willBuyTokens / didBuyTokens methods

### PR DESCRIPTION
**Pull request by lgalabru**
Hello there!

This is a backward compatible proposal for the Crowdsale#buyTokens method.
That way, subclasses of Crowdsale could just override willBuyTokens or didBuyTokens if they need some customisation, and avoid rewriting buyTokens.
Best,

Ludo

### CODE REVIEW

**Comment by frangio** [comment]
This is neat! Thanks @lgalabru.

Can you add tests to ensure that the three functions are called?

**Comment by lgalabru** [comment]
hi @frangio! sure, but how would you test such a thing? it's probably similar to  what we would want to have with Crowdsale#validPurchase, but there's no test for that.

**Comment by frangio** [comment]
I see your point, but I think it's somewhat different than `validPurchase` because in this case we want to guarantee that the functions are _called_. On the other hand, `validPurchase` is just the means to guarantee that only some purchases get through, and this we do test.

As for how to test it, I would create a mock contract inheriting from `Crowdsale` that emits an event in each of the functions. You can then check that the events are emitted.

A thought: what would you think about removing `canBuyTokens` and instead doing `require(validPurchase())` in `willBuyTokens`?

**Comment by lgalabru** [comment]
Roger that, thanks for the trick concerning the testing, I will do that.

Concerning merging canBuyTokens in willBuyTokens, I originally did that, but it implies that a developer overriding willBuyToken (and who probably just want to be notified that the buying will proceed) is responsible to call super.willBuyToken, otherwise the validPurchase is not called. 
I thought that decoupling the notification and the authorisation was more safe.

**Comment by frangio** [comment]
There are other places in the library where the developer must call `super`. For example, in [`FinalizableCrowdsale#finalization`](https://github.com/OpenZeppelin/zeppelin-solidity/blob/master/contracts/crowdsale/FinalizableCrowdsale.sol#L33-L37).

I agree this isn't ideal because there's no way to guarantee that a developer won't mess things up. But I think it's the best we can do at this moment. I've been thinking about providing a small linter-type program with OpenZeppelin that can check these kinds of rules.

**Comment by SylTi** [comment]
@frangio maybe this can be mitigated by using them both in SampleCrowdsale.sol?

**Comment by ajsantander** [comment]
@Igalabru did you manage to make any progress on these changes?

**Comment by nventuro** [comment]
Closing as stale. Also, our current `Crowdsale` model provides similar features to the ones suggested here.

**Pull request closed without merging**
